// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.4.1_@types+node@22.13.1_db0@0.2.1_mysql2@3.12.0__encoding_db5a3062506739fad16e081139d49bf1/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+image@1.9.0_ioredis@5.4.2_magicast@0.3.5_rollup@4.28.0/node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}