// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.4.1_@types+node@22.13.1_db0@0.2.1_mysql2@3.12.0__encoding_db5a3062506739fad16e081139d49bf1/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.4.1_@types+node@22.13.1_db0@0.2.1_mysql2@3.12.0__encoding_db5a3062506739fad16e081139d49bf1/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.4.1_@types+node@22.13.1_db0@0.2.1_mysql2@3.12.0__encoding_db5a3062506739fad16e081139d49bf1/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.4.1_@types+node@22.13.1_db0@0.2.1_mysql2@3.12.0__encoding_db5a3062506739fad16e081139d49bf1/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.4.1_@types+node@22.13.1_db0@0.2.1_mysql2@3.12.0__encoding_db5a3062506739fad16e081139d49bf1/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.4.1_@types+node@22.13.1_db0@0.2.1_mysql2@3.12.0__encoding_db5a3062506739fad16e081139d49bf1/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.4.1_@types+node@22.13.1_db0@0.2.1_mysql2@3.12.0__encoding_db5a3062506739fad16e081139d49bf1/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.4.1_@types+node@22.13.1_db0@0.2.1_mysql2@3.12.0__encoding_db5a3062506739fad16e081139d49bf1/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@pinia+nuxt@0.5.5_magicast@0.3.5_rollup@4.28.0_typescript@5.6.2_vue@3.5.13_typescript@5.6.2_/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.4.1_@types+node@22.13.1_db0@0.2.1_mysql2@3.12.0__encoding_db5a3062506739fad16e081139d49bf1/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../plugins/a.dayjs")> &
  InjectionType<typeof import("../../plugins/a.i18n")> &
  InjectionType<typeof import("../../plugins/animation")> &
  InjectionType<typeof import("../../plugins/ant")> &
  InjectionType<typeof import("../../plugins/api")> &
  InjectionType<typeof import("../../plugins/clamp")> &
  InjectionType<typeof import("../../plugins/domPurify")> &
  InjectionType<typeof import("../../plugins/error-handler")> &
  InjectionType<typeof import("../../plugins/error-reporting")> &
  InjectionType<typeof import("../../plugins/font")> &
  InjectionType<typeof import("../../plugins/import-worker")> &
  InjectionType<typeof import("../../plugins/monaco")> &
  InjectionType<typeof import("../../plugins/pdf-object")> &
  InjectionType<typeof import("../../plugins/poller")> &
  InjectionType<typeof import("../../plugins/redirect")> &
  InjectionType<typeof import("../../plugins/resizeDirective")> &
  InjectionType<typeof import("../../plugins/sentry")> &
  InjectionType<typeof import("../../plugins/state")> &
  InjectionType<typeof import("../../plugins/tele")> &
  InjectionType<typeof import("../../plugins/vue-qr-code-scanner")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
